# -*- coding: utf-8 -*-
"""Roboflow-Train-YOLOv5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDZ2xcTOgR39tGGs-EZ6i3RTs16wmzZQ
"""

import re
import random
import string

# --- Student 1: Length & Input Handling ---
def check_length_score(password):
    score = 0
    feedback = []
    length = len(password)

    if length >= 12:
        score = 40
    elif length >= 8:
        score = 20
    else:
        score = 10
        feedback.append("Password is too short (minimum 8 characters).")

    return score, feedback

# --- Student 2: Complexity & Regex Analysis ---
def check_complexity_score(password):
    score = 0
    feedback = []

    if re.search("[a-z]", password) and re.search("[A-Z]", password):
        score += 20
    else:
        feedback.append("Include both uppercase and lowercase letters.")

    if re.search("[0-9]", password):
        score += 20
    else:
        feedback.append("Add at least one number.")

    if re.search("[!@#$%^&*(),.?\":{}|<>]", password):
        score += 20
    else:
        feedback.append("Use special characters (e.g., @, #, $).")

    return score, feedback

# --- Bonus Feature: Random Strong Password Generator ---
def generate_suggested_password(length=16):
    characters = string.ascii_letters + string.digits + string.punctuation
    suggestion = ''.join(random.choice(characters) for i in range(length))
    return suggestion

# --- Student 3: Integration & Final Reporting ---
def run_password_checker():
    print("--- 🛡️ Advanced Password Security Toolkit ---")
    user_input = input("Enter password to test: ")

    # Run analysis
    length_score, length_feedback = check_length_score(user_input)
    complexity_score, complexity_feedback = check_complexity_score(user_input)

    total_score = length_score + complexity_score
    all_feedback = length_feedback + complexity_feedback

    # Display results
    print("\n" + "="*40)
    print(f"Final Security Score: {total_score}/100")

    if total_score >= 80:
        print("Rating: VERY STRONG ✅")
    elif total_score >= 50:
        print("Rating: MODERATE ⚠️")
    else:
        print("Rating: WEAK ❌")

    if all_feedback:
        print("\n💡 Suggestions for improvement:")
        for note in all_feedback:
            print(f"- {note}")

    # Display the automated suggestion
    print("\n" + "-"*40)
    print("✨ Need a more secure password?")
    print(f"Suggested Password: {generate_suggested_password()}")
    print("="*40)

# Execute the program
if __name__ == "__main__":
    run_password_checker()